/* AUTO-GENERATED by sync-engine next. Do not edit. */
import {
  defineGeneratedNextSyncConfig,
} from "@mintcd/sync-engine/next";
import type {
  InferDatabase,
} from "@mintcd/sync-engine/schema";

export const finalConfig = defineGeneratedNextSyncConfig({
  "formatVersion": 1,
  "databaseName": "html-annotation-sync",
  "endpoints": {
    "pull": "/api/sync/pull",
    "push": "/api/sync/push"
  },
  "serviceWorker": {
    "url": "/sw.js",
    "syncTag": "html-annotation-sync"
  },
  "schema": {
    "formatVersion": 1,
    "tables": {
      "annotations": {
        "primaryKey": [
          "id"
        ],
        "columns": {
          "id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "page_id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "exact": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "html": {
            "affinity": "text",
            "nullable": true,
            "generated": false
          },
          "created_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "updated_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "color": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "comment": {
            "affinity": "text",
            "nullable": true,
            "generated": false
          },
          "prefix": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "suffix": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          }
        }
      },
      "highlight_colors": {
        "primaryKey": [
          "color"
        ],
        "columns": {
          "color": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "semantics": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          }
        }
      },
      "page_notes": {
        "primaryKey": [
          "id"
        ],
        "columns": {
          "id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "page_id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "content": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "format": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "created_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "updated_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          }
        }
      },
      "pages": {
        "primaryKey": [
          "id"
        ],
        "columns": {
          "id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "url": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "title": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "number_of_scripts": {
            "affinity": "integer",
            "nullable": true,
            "generated": false
          },
          "created_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "updated_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "number_of_annotations": {
            "affinity": "integer",
            "nullable": true,
            "generated": false
          }
        }
      },
      "site_cookies": {
        "primaryKey": [
          "site_id"
        ],
        "columns": {
          "site_id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "cookie": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "updated_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          }
        }
      },
      "websites": {
        "primaryKey": [
          "id"
        ],
        "columns": {
          "id": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "origin": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "created_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "updated_at": {
            "affinity": "text",
            "nullable": false,
            "generated": false
          },
          "title": {
            "affinity": "text",
            "nullable": true,
            "generated": false
          }
        }
      }
    },
    "schemaHash": "sha256:081d2eb4c0325d950b0376f34e9d051fd63f64436338df5f054dac96f78be162"
  }
} as const);

export const replicaSchema = finalConfig.schema;
export type Database = InferDatabase<typeof replicaSchema>;
export type TableName = keyof Database;
export type Row<Table extends TableName> = Database[Table];
