/* AUTO-GENERATED by sync-engine generator. Do not edit. */
import { createRepo } from '@mintcd/sync-engine';

export const finalConfig = {
  swPath: "/sw.js"
};

type Schema = {
  "pages": {
    "id": string;
    "url": string;
    "title": string;
    "number_of_scripts": number | null;
    "created_at": string;
    "updated_at": string;
    "number_of_annotations": number | null;
  };
  "websites": {
    "id": string;
    "origin": string;
    "created_at": string;
    "updated_at": string;
  };
  "site_cookies": {
    "site_id": string;
    "cookie": string;
    "updated_at": string;
  };
  "annotations": {
    "id": string;
    "page_id": string;
    "text": string;
    "html": string | null;
    "created_at": string;
    "updated_at": string;
    "color": string;
    "comment": string | null;
    "position": Record<string, unknown> | null;
  };
  "operations": {
    "id": string;
    "entity": string;
    "op_type": string;
    "payload": string | null;
    "created_at": string;
    "processed": number;
    "attempts": number;
    "last_error": string | null;
    "client_id": string | null;
    "client_op_id": string | null;
    "sent_at": string | null;
    "undone": number;
    "instance_id": string | null;
  };
};
export const db = createRepo<Schema>();